# Site settings
title: Fliito Dev Blog
email: jeakwang@flitto.com
description: > # this means to ignore newlines until "baseurl:"
  플리토 개발 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeakwang.github.io/" # the base hostname & protocol for your site
github_username:  jeakwang

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8
paginate: 10