# Site settings
title: Flitto Devlop Blog

email: jeakwang@flitto.com
description: > # this means to ignore newlines until "baseurl:"
  안녕하세요. 플리토 개발자 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeakwang.github.io/" # the base hostname & protocol for your site
github_username:  jeakwang

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8
excerpt_separator: "http://jeakwang.github.io/seminar/2015/04/10/use%20req_tr.html"   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed